"use client";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';

import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
} from 'recharts';

// ✅ Fix: Import all of recharts and use ResponsiveContainer safely
import ResponsiveContainer from '@/components/dashboard/charts/ResponsiveContainerNoSSR';
import { mockBarChartData } from '@/lib/mock-data';

export function ChannelChart() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Performance by Channel</CardTitle>
        <CardDescription>
          Revenue generated by each marketing channel
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="h-[300px]">
          <ResponsiveContainer width="100%" height="100%">
            {((() => (
            <BarChart data={mockBarChartData}>
              <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
              <XAxis
                dataKey="name"
                className="text-xs text-muted-foreground"
                tick={{ fontSize: 12 }}
                angle={-45}
                textAnchor="end"
                height={60}
              />
              <YAxis
                className="text-xs text-muted-foreground"
                tick={{ fontSize: 12 }}
              />
              <Tooltip
                contentStyle={{
                  backgroundColor: 'hsl(var(--background))',
                  border: '1px solid hsl(var(--border))',
                  borderRadius: '6px',
                }}
              />
              <Bar
                dataKey="value"
                fill="#3b82f6"
                radius={[4, 4, 0, 0]}
              />
            </BarChart>
           )) as any)}
          </ResponsiveContainer>
        </div>
      </CardContent>
    </Card>
  );
}
